version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:16.04-curl-browsers
    steps:
      - checkout
      - run:
          name: Compile
          command: |
            gcc example.c
      - run:
          name: Test 1
          command: |
            ./test1.sh

      - run:
          name: Test 2
          command: |
            ./test2.sh
