version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-stretch
    steps:
      - checkout

      - run:
          name: Install basic utils
          command: |
            apt-get update && apt-get install -y build-essential
      - run:
          name: Compile
          command: |
            gcc example.c

      - run:
          name: Test 1
          command: |
            ./test1.sh
      - run:
          name: Test 2
          command: |
            ./test2.sh

      - run:
          name: Install aws cli
          command: |
            pip install awscli --upgrade --user
            export PATH=$HOME/.local/bin:$PATH

      - run:
          name: Upload to S3
          command: |
