version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - run:
          name: Print env 1
          command: printenv
      - run:
          name: Print env 2
          command: env

      - run:
          name: Install basic utils
          command: |
            apt-get update && apt-get install -y build-essential
      - run:
          name: Compile
          command: |
            gcc example.c

      - run:
          name: Test 1
          command: |
            ./test1.sh
      - run:
          name: Test 2
          command: |
            ./test2.sh
